sudo: required

language: node_js

node_js:
  - "7.8.0"

services:
  - docker

env:
  - DOCKER_IMAGE=chiswicked/achievements-service

install:
  - docker build -t $DOCKER_IMAGE .

script:
  - docker run $DOCKER_IMAGE test

after_success:
  - ./bin/report-code-quality
  - ./bin/push-docker-image `bash ./bin/package-version`
